default_stages: [commit]

repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus, --keep-percent-format]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - #
            pycodestyle ==2.9.1
          - #
            pyflakes ==2.5.0
          - #
            flake8-bandit ==4.1.1
          - #
            bandit ==1.7.4
          - #
            flake8-bugbear ==22.8.23
          - #
            flake8-comprehensions ==3.10.0
          - #
            flake8-docstrings ==1.6.0
          - #
            pydocstyle ==6.1.1

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        additional_dependencies:
          - #
            venv-run ==0.1.2
        entry: venv-run mypy
        types: [python]
        require_serial: true

      - id: pylint
        name: pylint
        language: python
        additional_dependencies:
          - #
            venv-run ==0.1.2
        entry: venv-run pylint
        types: [python]
        require_serial: true

  - repo: https://github.com/crate-ci/typos
    rev: v1.12.0
    hooks:
      - id: typos

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        args: [--msg-filename] # no need for --staged
        stages: [commit-msg]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.5
    hooks:
      - id: pymarkdown
        exclude: ^CHANGELOG\.md$
