default_stages: [commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        additional_dependencies:
          - venv-run==0.2.0
        entry: venv-run mypy .
        types: [python]
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/crate-ci/typos
    rev: v1.27.3
    hooks:
      - id: typos
        # TODO: to .typos.toml, https://github.com/crate-ci/typos/issues/347
        exclude: ^tests/cassettes/

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.16
    hooks:
      - id: pymarkdown
        exclude: ^CHANGELOG\.md$
