default_stages: [commit]

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.238
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        additional_dependencies:
          - #
            venv-run ==0.1.2
        entry: venv-run mypy
        types: [python]
        require_serial: true

  - repo: https://github.com/crate-ci/typos
    rev: v1.12.14
    hooks:
      - id: typos
        # TODO: to .typos.toml, https://github.com/crate-ci/typos/issues/347
        exclude: ^tests/cassettes/

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        args: [--msg-filename] # no need for --staged
        stages: [commit-msg]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.8
    hooks:
      - id: pymarkdown
        exclude: ^CHANGELOG\.md$
