[build-system]
requires = ["setuptools >=42", "wheel"]

[tool.black]
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = ["error"]
