#!/usr/bin/env python3

"""Print collection schedules."""

import argparse
import asyncio
import json
import sys
from datetime import datetime, timedelta, timezone

import icalendar

import pytekukko
from pytekukko.examples import example_argparser, example_client


def argparser() -> argparse.ArgumentParser:
    """Return an argument parser for the example.

    This is a separate function to facilitate shtab generated completions.
    """
    argparser = example_argparser(__doc__)
    _ = argparser.add_argument(
        "-i", "--icalendar", action="store_true", help="output iCalendar"
    )
    return argparser


# reportUnknownMemberType=false for Calendar.add, Event.add
# pyright: reportUnknownMemberType=false


async def run_example() -> None:
    """Run the example."""
    args = argparser().parse_args()

    client, cookie_jar, cookie_jar_path = example_client(args)

    async with client.session:
        data = [
            (service, await client.get_collection_schedule(service))
            for service in await client.get_services()
            if service.next_collection
        ]
        if not cookie_jar_path:
            await client.logout()

    if args.icalendar:
        now = datetime.now(tz=timezone.utc)
        cal = icalendar.Calendar.new(
            prodid=f"pytekukko/{pytekukko.__version__}",
            name="Jätekukko collections",
            url="https://tilasto.jatekukko.fi/indexservice2.jsp",
            method="PUBLISH",
        )
        # Remove the UID auto generated by new().
        # A random UUID each time is not desirable here,
        # as it is likely that the same .ical is re-published later with changed events.
        # UID should not contain any info that could identify a user,
        # and pretty much the only unique info here we have is the customer number which
        # isn't exactly that alone, but also likely not something one wants to publish.
        # Ref https://www.rfc-editor.org/info/rfc7986/#section-5.3
        cal.uid = None
        cal["X-WR-CALNAME"] = cal.calendar_name
        cal["X-WR-TIMEZONE"] = "Europe/Helsinki"
        for service, schedule in data:
            for date in schedule:
                event = icalendar.Event.new(
                    # Making use of the "pos" here is in a way similar to the customer
                    # number above, but seems more benign. So keep using it, also for
                    # backwards compatibility. Aside, might not be that great to have
                    # the date here in the UID, in case it changes...
                    uid=f"pytekukko-{service.pos}-{date}@scop.github.io",
                    summary=service.name,
                    stamp=now,
                    start=date,
                    end=date + timedelta(days=1),
                    url=cal.url,
                )
                cal.add_component(event)
        _ = sys.stdout.buffer.write(cal.to_ical())
    else:
        print(  # noqa: T201 # intentional
            json.dumps(
                [
                    {
                        "name": service.name,
                        "collection_schedule": [date.isoformat() for date in schedule],
                    }
                    for service, schedule in data
                ]
            )
        )

    if cookie_jar_path:
        cookie_jar.save(cookie_jar_path)


def main() -> None:
    """Run example in event loop."""
    asyncio.run(run_example())


if __name__ == "__main__":
    main()
