style = "conventional"
allowed_types = [
  "fix",
  "feat",
  "chore",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  # add revert, ci, build: https://github.com/crate-ci/committed/pull/420
  "revert",
  "ci",
  "build",
]
ignore_author_re = '\[bot\]'
subject_capitalized = false
