name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@08f8a44771add9537499e9325dca0fe1479c2480 # main
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          activate-environment: true
      - name: Install Python dev dependencies
        run: uv pip install --upgrade --requirements requirements/dev-requirements.txt
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - run: lefthook run pre-commit --all-files --no-tty
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          commit-message: "chore: autofix.ci automated fixes"
