name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv
          key: >-
            pip+venv
            ${{ hashFiles(
                'pyproject.toml', 'requirements-dev.txt',
                'requirements-test.txt', '.github/requirements.txt'
            ) }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: >-
            pre-commit
            ${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: |
          set -euo pipefail
          python3 -m venv venv
          source venv/bin/activate
          set -x
          python3 -m pip install -Ur .github/requirements.txt
          pre-commit install-hooks
      - name: Run linters
        run: |
          set -euo pipefail
          source venv/bin/activate
          set -x
          rc=0
          gitlint --commits "origin/${GITHUB_BASE_REF:-main}..HEAD" \
            || rc=1
          pre-commit run --all-files --color always --show-diff-on-failure \
            || rc1=1
          exit $rc

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12.0-alpha - 3.12"
          - "pypy-3.9"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .nox
          key: >-
            ${{ runner.os }} pip ${{ matrix.python-version }}
            ${{ hashFiles('pyproject.toml', 'requirements-test.txt') }}
      - uses: excitedleigh/setup-nox@v2.1.0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          v="${{ matrix.python-version }}"
          v=${v##* }  # "3.12.0-alpha - 3.12" -> "3.12"
          v=${v//-}   # "pypy-3.9" -> "pypy3.9"
          nox --force-color --python "$v"
        env:
          PYTEST_ADDOPTS: --vcr-record=none --color=yes
