name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
      LEFTHOOK_QUIET: meta,execution
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # for commit message checks
      - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
        with:
          activate-environment: true
      - name: Install Python dev dependencies
        run: uv pip install --upgrade --requirements requirements/dev-requirements.txt
      - uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
      - name: Check code
        run: lefthook run pre-commit --all-files --force --no-tty
      - name: Check commit messages
        run: lefthook run commit-msgs-on-pr-branch --no-tty
        if: ${{ github.event_name == 'pull_request' }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14.0-alpha - 3.14"
          - "pypy-3.10"
          - "pypy-3.11"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
      - uses: wntrblm/nox@2254a1ee500bbf66c2a5e4ff5dad030b9f579dcd # 2025.05.01
        with:
          python-versions: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          v="${{ matrix.python-version }}"
          v=${v##* }  # "3.12.0-alpha - 3.12" -> "3.12"
          v=${v//-}   # "pypy-3.9" -> "pypy3.9"
          nox --force-color --python "$v"
        env:
          NOX_DEFAULT_VENV_BACKEND: uv
          PYTEST_ADDOPTS: --color=yes
