name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # for commit message checks
      - uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5.1.0
        with:
          cache-dependency-glob: |
            requirements/dev-requirements.txt
            requirements/test-requirements.txt
            pyproject.toml
      - uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10
      - name: Check commit messages
        run: lefthook run commit-msgs-on-pr-branch --no-tty
        if: ${{ github.event_name == 'pull_request' }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14.0-alpha - 3.14"
          - "pypy-3.10"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5.1.0
        with:
          cache-dependency-glob: |
            pyproject.toml
            requirements/test-requirements.txt
      - uses: wntrblm/nox@1199ab3892b1a941f80ff052083d0a571abed79d # 2024.10.09
        with:
          python-versions: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          v="${{ matrix.python-version }}"
          v=${v##* }  # "3.12.0-alpha - 3.12" -> "3.12"
          v=${v//-}   # "pypy-3.9" -> "pypy3.9"
          nox --force-color --python "$v"
        env:
          NOX_DEFAULT_VENV_BACKEND: uv
          PYTEST_ADDOPTS: --vcr-record=none --color=yes
