name: Lint commits

on:
  pull_request:

permissions: {}

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@08f8a44771add9537499e9325dca0fe1479c2480 # main
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - run: lefthook run commits-on-pr-branch --no-tty
