name: Lint commits

on:
  pull_request:

permissions: {}

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@08f8a44771add9537499e9325dca0fe1479c2480 # main
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - run: lefthook run commits-on-pr-branch --no-tty
