name: release

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release_please
        with:
          release-type: python
          package-name: pytekukko
          pull-request-title-pattern: "chore: release${component} ${version}"
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      sha: ${{ steps.release_please.outputs.sha }}

  pypi_upload:
    runs-on: ubuntu-latest
    needs: release_please
    if: needs.release_please.outputs.release_created
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release_please.outputs.sha }}
      - name: Create release assets
        run: |
          set -euxo pipefail
          python3 -m pip install -U build
          python3 -m build
          ls dist
      - uses: pypa/gh-action-pypi-publish@v1.8.8
