name: release

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release_please
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      sha: ${{ steps.release_please.outputs.sha }}

  pypi_upload:
    runs-on: ubuntu-latest
    needs: release_please
    if: needs.release_please.outputs.release_created
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ needs.release_please.outputs.sha }}
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
        with:
          activate-environment: true
      - name: Create release assets
        run: |
          set -euxo pipefail
          uv pip install --upgrade build
          uv run python3 -m build
          ls dist
      - uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
