name: release

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        id: release_please
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      sha: ${{ steps.release_please.outputs.sha }}

  pypi_upload:
    runs-on: ubuntu-latest
    needs: release_please
    if: needs.release_please.outputs.release_created
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ needs.release_please.outputs.sha }}
      - name: Create release assets
        run: |
          set -euxo pipefail
          python3 -m pip install -U build
          python3 -m build
          ls dist
      - uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
